[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.22"
optimizer = true
optimizer_runs = 200
evm_version = "paris"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Rootstock Network Configuration
[rpc_endpoints]
rootstock_mainnet = "https://public-node.rsk.co"
rootstock_testnet = "https://public-node.testnet.rsk.co"

[etherscan]
rootstock_mainnet = { api_url = "https://blockscout.com/rsk/mainnet/api", key = "${ROOTSTOCK_API_KEY}" }
rootstock_testnet = { api_url = "https://blockscout.com/rsk/testnet/api", key = "${ROOTSTOCK_API_KEY}" }

# Test configuration
[profile.ci]
optimizer = true
optimizer_runs = 200
via_ir = false
